env = Environment()

debug = ARGUMENTS.get('debug', 0)
if int(debug):
    env.Append(CXXFLAGS = ["-D_DEBUG"])

env.Append(CXXFLAGS = ["-std=c++0x", "-O3"])
env.Append(CXXFLAGS = ["-Wall", "-Werror", "-g"])
env.Append(CXXFLAGS = ["-Wno-format-security"])

env.Append(CPPPATH = [".", "puck"])
env.Append(LINKFLAGS = ["-g", "-pthread"])

gtest_path = "contrib/gmock/gtest"
gtest_include = gtest_path + "/include"
gtest_src = gtest_path + "/src"

gtest = env.Object(
    "lib/gtest.o",
    gtest_src + "/gtest-all.cc",
    CPPPATH = [gtest_path, gtest_include]
)

gtest_main = env.Object(
    "lib/gtest_main.o",
    gtest_src + "/gtest_main.cc",
    CPPPATH = [gtest_path, gtest_include]
)

puck_path = "contrib/puck"
puck_include = puck_path + "/puck"

run_ut = env.Program(
    "test/run_ut",
    Glob("test/ut/*.cc") + [gtest_main],
    LIBS = [gtest],
    CPPPATH = env["CPPPATH"] + [gtest_include]
)
